mkdocs.yml
Reorders authorino nav items, for consistency with other sections. First `How-to`, then `Reference`.
=> reorders authorino nav items

mkdocs.yml
Adds how-to guides for TLSPolicy and DNSPolicy, from the MGC repo.
To test locally, install deps via the README and run `mkdocs serve` - you should see two new guides underneath MGC>How-To
=> Add TLSPolicy and DNSPolicy how-to guides

docs/getting-started.md
=> update to specify account and user permissions for created root domain

mkdocs.yml
`Metrics Federation` will be removed [https://github.com/Kuadrant/multicluster-gateway-controller/pull/598](https://github.com/Kuadrant/multicluster-gateway-controller/pull/598)
Should be merged after that one?
=> Metrics federation doc removed

mkdocs.yml
- New auth policy overview and API reference
- Removed redundant `<X>Policy ` prefix from submenu titles
- Re-added section "RFCs"
- Authorino non-Kuadrant user guides moved to component-specific section
=> AuthPolicy v2 docs

README.md, docs/getting-started.md
**Summary**
* Fixed issue with copying/pasting the getting started curl command when using zsh (see [slack thread](https://kubernetes.slack.com/archives/C05J0D0V525/p1698836281419569) for context)
* Updated README to reference access URL for running docs locally
=> Documentation updates

mkdocs.yml
Enables [`md_in_html`](https://python-markdown.github.io/extensions/md_in_html/) Python-Markdown extension.
Provided an attribute `markdown="1"` is added to the HTML blocks that contain markdown content inside, that content will render properly with this extension. E.g.:
**Before**
<br/>
<br/>
**After**
<br/>
<br/>
By also editing the original Markdown file https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/kubernetes-tokenreview.md as such:
```diff
diff --git a/docs/user-guides/kubernetes-tokenreview.md b/docs/user-guides/kubernetes-tokenreview.md
index 718d80a1..a70caa9f 100644
--- a/docs/user-guides/kubernetes-tokenreview.md
+++ b/docs/user-guides/kubernetes-tokenreview.md
@@ -2,7 +2,7 @@
Validate Kubernetes Service Account tokens to authenticate requests to your …
```
=> Activate md_in_html extension

mkdocs.yml
Freezing only MGC for now, as I think some docs improvements are in progress on other components.
=> Freeze mgc branch to release

mkdocs.yml
Updated "How-to Guides/Advanced DNS based LoadBalancing" section to point to multicluster-gateway-controller/docs/how-to/multicluster-loadbalanced-dnspolicy.md. 
Removed "How-to Guides/GEO Based DNS LoadBalancing" and "How-to Guides/Weighted DNS LoadBalancing" since it's all dealt with in the one doc (Also couldn't get the links to work).
=> Update DNS docs link

mkdocs.yml
API quickstart doc.
WIP at the moment.
=> API Quickstart doc

docs/index.md, mkdocs.yml, requirements.txt
Adding some updates to bring some of our videos from our YouTube channel into the docs site.
Also bumps the versions of some of our mkdocs deps to remove some warnings.
Some screenshots:
=> docs videos & plugin bumps

mkdocs.yml
Fixing some 404's for some of the detailed guides for kuadrantctl.
=> import docs/* for kuadrantctl

mkdocs.yml
Part of https://github.com/Kuadrant/kuadrantctl/issues/53
Adds existing guides to sub nav
=> Add kuadrantctl sub guides to side nav

mkdocs.yml
Change from `APICurio` to `Apicurio Studio`
=> Branding change for Apicurio Studio

docs/getting-started-multi-cluster-ocm.md, docs/getting-started-multi-cluster.md, mkdocs.yml
Depends on quickstart-setup changes in https://github.com/Kuadrant/kuadrant-operator/pull/590 & mgc links changes in https://github.com/Kuadrant/multicluster-gateway-controller/pull/797
Part of https://github.com/Kuadrant/kuadrant-operator/issues/495
The intention is to:
- update the existing guide to allow for changes to how multi cluster dns is done (without ocm)
- have a unified script for setting up 1 or many clusters to avoid code duplication
- be able to use the already existing follow-on 'secure-protect-connect' guide in each & every additional cluster (updated in https://github.com/Kuadrant/kuadrant-operator/pull/590)
- move all ocm & mgc related content into a new sub-section of the 'How to' sidenav item.
=> Update multicluster guide to reuse quickstart-setup script

.github/workflows/build.yaml, README.md, docs/assets/stylesheets/extra.css, mkdocs.yml, overrides/main.html, overrides/partials/footer.html, requirements.txt
Test locally:
```bash
git checkout 0.6.1
mike deploy 0.6.1
mike deploy 0.6.1 "0.6.1 (stable)"
git checkout main
mike deploy 0.7.0 -t "0.7.0 (dev)"
mike set-default 0.6.1
mike serve
```
=> Adding mike support for multi-versioned docs

docs/getting-started-single-cluster.md
Latest docs changes have not been tested with older 0.6.1 release.
This change will ease the transition to the upcoming release.
=> Use main ref until next release to simplify testing

mkdocs.yml
https://deploy-preview-112--graceful-kangaroo-3c9c10.netlify.app/dns-operator/docs/provider/
=> re-add dns-provider guide

.github/workflows/build.yaml
- Run `build` step for all PRs
- Only run `deploy` for merges to `main`
=> builds for all branches, deploy only for main.

mkdocs.yml
#122 
Replaced broken links in v0.6.1 docs.
( Within sidebar )
How-to Guides --> DNS configuration and load balancing ...
--> Advanced DNS based LoadBalancing
--> GEO Based DNS LoadBalancing
-->  Weighted DNS LoadBalancing
**REPLACED BY**
How-to Guides --> DNS configuration and load balancing ...
--> Multicluster LoadBalanced DNSPolicy
Which contains links to Advanced, GEO and Weighted LoadBalancing that can now be accessed by the index bar on the right . 
Run `mkdocs serve` and navigate to aforementioned sidebar refs and ensure content is accessible .
=> Fixed broken links in v0.6.1 docs by replacing them with a single link that includes reference to all 3. 

mkdocs.yml
We seemed to have single and double quotes. My editor freaked and set them all to single. Hope this is ok
Signed-off-by: craig <cbrookes@redhat.com>
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED
=> add a dnsprovider setup doc

.github/workflows/mike-redeploy.yaml
- adds cron schedule for midnight UTC
- sets inputs to 'dev' version and 'main' branch if scheduled
- bypasses permission check if run by github bot
=> Run nightly deploy

Dockerfile, README.md, requirements.txt
Python environment setup and dependencies can be difficult to manage for those who want to dip and out of docs. Added an option to run `mike`/`mkdocs` in a container.
=> Add a dockerfile, instructions to run mkdocs locally + in podman/docker

mkdocs.yml
Part of https://github.com/Kuadrant/docs.kuadrant.io/issues/25
Move Authorino specific user guides mentioning `AuthConfig` to under Authorino -> User Guides instead since there'll probably be user confusion with `AuthPolicy`
We'll create some `AuthPolicy` specific guides from the `Authorino` guides that will be used for Kuadrant Operator as part of https://github.com/Kuadrant/docs.kuadrant.io/issues/25
=> refactor: move authorino specfic guides to under Authorino User Guides

.github/workflows/mike-redeploy.yaml
This should prevent deploys where things like 404 links get through the nightly deploy
=> Do a strict build before nightly deploy

mkdocs.yml
Moves 2 dns guides out of the reference section of the docs (see before/after screenshots).
1 of the guides was already in the guides section as well (so in 2 places at once), which was confusing if you reached it through the reference section as the side nav would change to the guides area.
I changed the order of the guides to what I thought made more sense as well. The guide for configuring a dns provider is above the guide for configuring the gateway
I also added in a few guides that landed on the v1.0.x branch in https://github.com/Kuadrant/docs.kuadrant.io/commit/a629b43646f5031590034c495e13017d0ec56bfc#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R144, but not on main.
before
after
=> DNS guides nav update

mkdocs.yml
The quickstart has served its purpose at an earlier stage of the kuadrant project, but is not been progressed passed the experimental stage.
It references older versions of the APIs that are not compatible with v1.
Let's remove it.
=> Remove experimental API Quickstart

mkdocs.yml
Since the [removal](https://github.com/Kuadrant/kuadrant-operator/pull/1091) of the (out of date) install on k8s doc, we should link to something.
The steps for the helm package on artifacthub work and should suffice as a stopgap for now.
Also, renaming the Openshift install guide to 'OLM on OpenShift' to show it's a different installation mechanism than Helm.
In future, the OLM guide should be reworked for both k8s & OpenShift use.
=> Temp fix for k8s install doc removal

OWNERS, mkdocs.yml
Split out api/references and concepts to follow the diataxis structure
=> Sperating concepts and api/references 

mkdocs.yml
Closes https://github.com/Kuadrant/kuadrant-operator/issues/1097
This PR splits out the 'How-to Guides' section into 'Tutorials' and 'Guides'.
Tutorials have been identified, as per diataxis compass (see https://github.com/Kuadrant/kuadrant-operator/issues/1097#issuecomment-2583319044), and moved to a new 'Tutorials' nav section, while the remaining content has been left in the (now renamed) 'Guides' nav section.
The content has not been changed in this PR.
Some nav titles have been updated to match the title in the doc.
=> Move all tutorial docs into new Tutorials section

mkdocs.yml
This change moves 2 observability docs out of the 'Guides' nav section as they are moreso reference material.
The 'APIs' section is also renamed to 'APIs & Reference' to show that docs in that section are not just api docs (a type of reference material), but more broad than that, to accommodate the 'Metrics' doc specifically.
=> Move observability reference material

CONTRIBUTING.md, README.md, style_guide.md
Closes https://github.com/Kuadrant/kuadrant-operator/issues/1118
The style guide content is a combination of some conversations on a different channel and some of the guidelines from https://kubernetes.io/docs/contribute/style/style-guide/
=> Add some contributing notes and a style guide

mkdocs.yml, requirements.txt
Related to #170,
though it doesn't aim to address that issue in a general way.
The changes here:
- add the [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects) plugin
- add redirects for the getting started, install and "Secure, Connect & Protect" tutorials that have changed path since previous versions
For running locally, I believe a new build of the `quay.io/kuadrant/docs.kuadrant.io:latest` image will be needed with `pip install` having been run.
To run this locally until then, you'll need to prefix any existing commands with `pip install -r requirements.txt &&`
For example:
```bash
docker run \
-v "$(pwd):/docs" \
-v "$HOME/.gitconfig:/opt/app-root/src/.gitconfig:ro" \
-v "$HOME/.ssh:/opt/app-root/src/.ssh:ro" \
-p 8000:8000 quay.io/kuadrant/docs.kuadrant.io:latest \
"pip …
```
=> Add redirects plugin & install/scp redirects

docs/install-olm.md, mkdocs.yml, validate_imports.py
- Cleanup dangling imports, remove globs
- removing glob imports, added script to detect dangling imports, generates explicit multirepo imports from the nav:
- Can be run manually: `python3 validate_imports.py`
=> removing glob imports, added script to detect dangling imports

mkdocs.yml
Adds reference docs and a tutorial for `TokenRateLimitPolicy`
part of:
https://github.com/Kuadrant/kuadrant-operator/issues/1344
=> Adding TokenRateLimitPolicy ref + tutorial
